### ISSUE TITLE
Supporting Arrays in Ch. 7

### ISSUE THREAD

**Issue by maherali** [Flight-School/Guide-to-Swift-Codable-Sample-Code#1]
The following:
struct Planes: Codable {
    var planes: [Plane]
}

let planes = [plane]
let e = MessagePackEncoder()
let d = try! e.encode(planes)

print(d.map{ String(format:"%2X", $0) })

result in ["90"]

I don't see nested containers are supported. Am I missing something?

**Comment by mattt** [comment]
`0x90` is the format byte for a fixed-width array with 0 elements. There's not enough context here to reproduce this issue, so I can't say what's causing this...

If you believe that this is indeed a bug, please submit an issue (or even better, a PR with a failing test case) to the main repository for the MessagePack library: https://github.com/Flight-School/MessagePack. Thanks!
